title:  Will Whitney
author:
  name: 'Will Whitney'
  twitter:  wfwhitney

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'learning-4'

google-ID: 'UA-104146434-1'

menu:
- {name: 'Home', url: '/'}
# - {name: 'About', url: 'menu/about.html'}
- {name: 'Blog', url: '/menu/blog.html'}
# - {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/willwhitney'}
- {icon: 'twitter', link: 'https://twitter.com/wfwhitney'}
- {icon: 'envelope', link: 'mailto:wfwhitney@gmail.com'}
# - {icon: 'rss', link: '/feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
